- name: blocked
  color: 'd93f0b'
- name: released
  color: 'ededed'
- name: next
  color: '5d3fd3'
- name: bug
  color: 'd73a4a'
- name: enhancement
  color: 'a2eeef'
- name: help wanted
  color: '008672'
- name: good first issue
  color: '7057ff'
- name: documentation
  color: '0075ca'
- name: question
  color: 'd876e3'
- name: duplicate
  color: 'cfd3d7'
- name: wontfix
  color: 'ffffff'
- name: spam
  color: 'e4e669'
- name: off topic
  color: 'e4e669'
- name: needs triage
  color: 'fbca04'
- name: needs investigation
  color: 'fbca04'
- name: breaking change
  color: 'b60205'
- name: performance
  color: 'f9d0c4'
- name: security
  color: 'b60205'
- name: refactor
  color: 'c5def5'
- name: automation
  color: 'bfdadc'
- name: repo-assist
  color: 'bfdadc'
