name: Login to GHCR
description: Login to GitHub Container Registry (GHCR)
author: devantler-tech
inputs:
  github-token:
    description: GitHub token with packages:read (or packages:write) scope
    required: true
runs:
  using: composite
  steps:
    - name: 🔑 Login to GHCR
      uses: step-security/docker-login-action@6aa05fe688caf2c58e784663f01b3415ced503e8 # v3.7.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
