name: Enable Auto Merge on PR
description: Approve and auto-merge PRs from specific bots/users
author: devantler-tech
inputs:
  app-id:
    description: GitHub App ID
    required: true
  app-private-key:
    description: GitHub App Private Key
    required: true
  github-token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - name: 🔑 Generate GitHub App Token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      id: app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.app-private-key }}

    - name: ✅ Approve pull request
      uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
      with:
        github-token: ${{ inputs.github-token }}

    - name: 🤖 Enable auto-merge
      shell: bash
      run: gh pr merge --auto --squash ${{ github.event.number }}
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
