#!/usr/bin/env bash
# Regenerates the bad-input fixtures for test-govulncheck-main-coverage-blocks.sh.
#
# Every fixture is emitted from ONE base, so a fixture differs from `good.yaml` only in
# the field this script varies for it. That is the property that makes the negative test
# meaningful: if a fixture drifted in some other way too, its failure would no longer
# isolate the check it is named for. `good.yaml` is the control — the blocks test asserts
# the guard PASSES it, so a guard that rejects everything cannot pass the suite either.
#
# Run from the repository root:  bash .github/tests/govulncheck-main-coverage-fixture/generate.sh

set -euo pipefail

cd "$(dirname "$0")"

GOOD_GATE="github.repository != 'x/y'
      && ((
        (
          needs.changes.outputs.go == 'true'
          || (
            (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
            && needs.changes.outputs.govulncheck == 'true'
          )
        )
        && github.event_name == 'pull_request'
      ) || (
        (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
        && needs.changes.outputs.go != ''
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      ))"

GOOD_GO_FILTER="            go:
              - '**/*.go'"

GOOD_VULN_FILTER="            govulncheck:
              - '.govulncheck-allow.txt'
              - '**/.govulncheck-allow.txt'"

GOOD_OUTPUTS="      go: \${{ steps.filter.outputs.go }}
      govulncheck: \${{ steps.filter.outputs.govulncheck }}"

# The scanner has to be pointed at the allowlist the trigger fired on. The action resolves
# its path inputs from the checkout root rather than from `work-dir`, so the value must be
# composed from `inputs.working-directory`: a bare literal reaches the ROOT allowlist while
# the detection step — a `run:` step, so it honours defaults.run.working-directory — reports
# the NESTED one as present.
GOOD_ALLOW_FILE="\${{ steps.govulncheck-allow.outputs.present == 'true' && format('{0}/.govulncheck-allow.txt', inputs.working-directory || '.') || '' }}"
ROOT_ONLY_ALLOW_FILE="\${{ steps.govulncheck-allow.outputs.present == 'true' && '.govulncheck-allow.txt' || '' }}"

# emit <file> <defect-description> <input-default> <go-filter> <vuln-filter> <outputs> <gate> [allow-file]
emit() {
  local name="$1" defect="$2" input_default="$3" go_filter="$4" vuln_filter="$5" outputs="$6" gate="$7"
  local allow_file="${8:-$GOOD_ALLOW_FILE}"
  cat > "$name" <<EOF
# FIXTURE — input for test-govulncheck-main-coverage-blocks.sh. Generated by generate.sh.
# Not a real workflow: it lives outside .github/workflows/ so no gate ever scans it.
#
# Defect: ${defect}
name: fixture
on:
  workflow_call:
    inputs:
      scan-default-branch:
        required: false
        type: boolean
        default: ${input_default}
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
${outputs}
    steps:
      - id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
${go_filter}
${vuln_filter}
  govulncheck:
    needs: [changes]
    runs-on: ubuntu-latest
    if: |
      ${gate}
    steps:
      - id: govulncheck-allow
        run: 'true'
      - uses: devantler/govulncheck-action@v0
        with:
          allow-file: ${allow_file}
EOF
}

# ── The control: everything correct. The guard must PASS this one. ────────────────
emit good.yaml \
  "none — this is the control, and the guard must pass it." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" "$GOOD_GATE"

# ── 1. A top-level event equality vetoes every arm, opt-in included. ──────────────
emit event-gated.yaml \
  "an event equality AND-ed at the TOP level, so no opt-in can ever reach the default-branch scan." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" \
  "github.repository != 'x/y'
      && github.event_name == 'pull_request'
      && ((
        (
          needs.changes.outputs.go == 'true'
          || (
            (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
            && needs.changes.outputs.govulncheck == 'true'
          )
        )
        && github.event_name == 'pull_request'
      ) || (
        (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
        && needs.changes.outputs.go != ''
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      ))"

# ── 2. No default-branch clause at all: the path filter is the only gate. ─────────
emit no-default-branch-clause.yaml \
  "no default-branch clause, so a non-Go push to the default branch reports green unscanned. Trips several coupled assertions; the blocks test pins the primary one." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" \
  "github.repository != 'x/y'
      && ((
        (
          needs.changes.outputs.go == 'true'
          || (
            (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
            && needs.changes.outputs.govulncheck == 'true'
          )
        )
        && github.event_name == 'pull_request'
      ) || (
        (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
        && needs.changes.outputs.go != ''
      ))"

# ── 3. The opt-in input is declared but the gate never consults it. ───────────────
# The pull-request arm keeps the UNGATED allowlist form here on purpose: this fixture's
# defect is that the gate never references the opt-in input at all, so injecting the flag
# into its allowlist term — as every other fixture carries it — would make the flag
# referenced and stop the assertion this fixture exists to pin from firing.
emit flag-not-referenced.yaml \
  "the gate never references the opt-in input, so the default-branch scan lands on every consumer at once. Trips several coupled assertions; the blocks test pins the primary one." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" \
  "github.repository != 'x/y'
      && ((
        (needs.changes.outputs.go == 'true' || needs.changes.outputs.govulncheck == 'true')
        && github.event_name == 'pull_request'
      ) || (
        needs.changes.outputs.go != ''
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      ))"

# ── 4. The flag AND-ed at the top level removes the scan everyone has today. ──────
emit flag-and-ed-at-top-level.yaml \
  "the opt-in input AND-ed at the TOP level, so a caller that does not opt in loses its existing pull-request scan." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" \
  "github.repository != 'x/y'
      && inputs.scan-default-branch
      && ((
        (
          needs.changes.outputs.go == 'true'
          || (
            (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
            && needs.changes.outputs.govulncheck == 'true'
          )
        )
        && github.event_name == 'pull_request'
      ) || (
        (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
        && needs.changes.outputs.go != ''
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      ))"

# ── 5. The path filter AND-ed at the top level makes the OR-arm decorative. ───────
emit default-branch-and-ed.yaml \
  "the path filter AND-ed at the TOP level, so a default-branch run with no Go paths changed is still skipped." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" \
  "github.repository != 'x/y'
      && needs.changes.outputs.go == 'true'
      && ((
        needs.changes.outputs.govulncheck == 'true'
        && github.event_name == 'pull_request'
      ) || (
        (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      ))"

# ── 5b. The same veto, written as a function call rather than a comparison. ───────
# This is what `defun` in the guard exists for. A GitHub expression may test the path
# filter with `contains(...)` instead of `==`, and a function call's parentheses are
# lexically identical to grouping parentheses. Without normalising them first, the
# group-stripper deletes the whole call as if it were a parenthesised group, the term
# vanishes from the top level, and this veto goes unreported.
emit path-filter-inside-function-call.yaml \
  "the path filter AND-ed at the TOP level inside a function call, so it vetoes the default-branch arm while hiding from a naive paren-stripper." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" \
  "github.repository != 'x/y'
      && contains(fromJSON('[\"true\"]'), needs.changes.outputs.go)
      && ((
        (
          needs.changes.outputs.go == 'true'
          || (
            (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
            && needs.changes.outputs.govulncheck == 'true'
          )
        )
        && github.event_name == 'pull_request'
      ) || (
        (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
        && needs.changes.outputs.go != ''
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      ))"

# ── 6. A top-level ref predicate excludes the default branch anyway. ──────────────
emit top-level-ref-predicate.yaml \
  "a ref predicate AND-ed at the TOP level, which excludes the default branch whatever the OR-ed clause says." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" \
  "github.repository != 'x/y'
      && github.ref != 'refs/heads/main'
      && ((
        (
          needs.changes.outputs.go == 'true'
          || (
            (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
            && needs.changes.outputs.govulncheck == 'true'
          )
        )
        && github.event_name == 'pull_request'
      ) || (
        (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
        && needs.changes.outputs.go != ''
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      ))"

# ── 7. The flag gates an arm that is not the new capability. ──────────────────────
emit flag-gates-wrong-arm.yaml \
  "the opt-in input gates the pull-request arm while the default-branch arm is unguarded, so the new scan is reachable without opting in." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" \
  "github.repository != 'x/y'
      && ((
        (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
        && (needs.changes.outputs.go == 'true' || needs.changes.outputs.govulncheck == 'true')
        && github.event_name == 'pull_request'
      ) || (
        needs.changes.outputs.go != ''
        && github.event_name == 'pull_request'
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      ))"

# ── 8. An extra arm fires on pushes for callers that never opted in. ──────────────
emit unflagged-arm-not-pr-gated.yaml \
  "a third OR-arm that is neither gated by the opt-in input nor restricted to pull requests, so it runs for every consumer." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" \
  "github.repository != 'x/y'
      && ((
        (
          needs.changes.outputs.go == 'true'
          || (
            (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
            && needs.changes.outputs.govulncheck == 'true'
          )
        )
        && github.event_name == 'pull_request'
      ) || (
        (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
        && needs.changes.outputs.go != ''
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      ) || (
        needs.changes.outputs.go == 'true'
        && github.event_name == 'push'
      ))"

# ── 9. A flag that defaults to true is not an opt-in. ─────────────────────────────
emit flag-defaults-true.yaml \
  "the opt-in input defaults to true, so the behaviour change lands on every consumer the moment it merges." \
  true "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" "$GOOD_GATE"

# ── 10. The nested allowlist form is missing. ─────────────────────────────────────
emit missing-allowlist-entries.yaml \
  "the govulncheck filter omits the nested allowlist form, so an allowlist edit in a module selected by working-directory skips the scan." \
  false "$GOOD_GO_FILTER" \
  "            govulncheck:
              - '.govulncheck-allow.txt'" \
  "$GOOD_OUTPUTS" "$GOOD_GATE"

# ── 11. The allowlist widens the shared `go` output. ──────────────────────────────
emit allowlist-in-shared-go-filter.yaml \
  "the allowlist is listed in the shared 'go' filter, so an allowlist-only commit runs tidy, lint, deadcode, tests and coverage in every consumer." \
  false \
  "            go:
              - '**/*.go'
              - '.govulncheck-allow.txt'
              - '**/.govulncheck-allow.txt'" \
  "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" "$GOOD_GATE"

# ── 12. The dedicated output exists but the gate never consults it. ───────────────
emit govulncheck-output-not-consumed.yaml \
  "the govulncheck filter output is produced but never read by the gate, so an allowlist-only commit still skips the scan that reads it." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" \
  "github.repository != 'x/y'
      && ((
        needs.changes.outputs.go == 'true'
        && github.event_name == 'pull_request'
      ) || (
        (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
        && needs.changes.outputs.go != ''
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      ))"

# ── 13. The dedicated output is never exposed, so the trigger silently never fires. ─
emit missing-govulncheck-output.yaml \
  "the changes job never exposes the govulncheck output, so needs.changes.outputs.govulncheck is always empty." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" \
  "      go: \${{ steps.filter.outputs.go }}" \
  "$GOOD_GATE"

# ── 14. The allowlist trigger fires without opting in. ────────────────────────────
# The mirror of fixture 8: there an ungated arm fired on pushes, here the allowlist term
# sits in the pull-request arm un-gated, so an allowlist-only PR schedules the scan in
# every consumer that passed nothing. Both tokens are present, and OR-ed rather than
# AND-ed with the flag — the shape a co-occurrence check would wave through.
emit allowlist-trigger-not-flag-gated.yaml \
  "the allowlist term is OR-ed into the pull-request arm without the opt-in input, so an allowlist-only pull request runs the scan for every consumer that never opted in." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" \
  "github.repository != 'x/y'
      && ((
        (needs.changes.outputs.go == 'true' || needs.changes.outputs.govulncheck == 'true')
        && github.event_name == 'pull_request'
      ) || (
        (inputs.scan-default-branch == true || inputs.scan-default-branch == 'true')
        && needs.changes.outputs.go != ''
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      ))"

# ── 15. The scan is pointed at the wrong allowlist. ───────────────────────────────
# The gate is correct and the nested pattern triggers, but the scanner still receives a
# checkout-root-relative literal, so a nested module's risk acceptance is dropped and the
# scan blocks on an advisory that was already accepted.
emit allow-file-not-working-dir-relative.yaml \
  "allow-file is a bare root-relative literal, so a nested module's allowlist triggers the scan but is not the file the scanner reads." \
  false "$GOOD_GO_FILTER" "$GOOD_VULN_FILTER" "$GOOD_OUTPUTS" "$GOOD_GATE" \
  "$ROOT_ONLY_ALLOW_FILE"

echo "regenerated $(find . -maxdepth 1 -name '*.yaml' | wc -l | tr -d ' ') fixtures"
