name: setup-ksail-action
description: |
  Installs KSail CLI via Homebrew

runs:
  using: "composite"
  steps:
    - name: 📦 Setup Homebrew
      uses: Homebrew/actions/setup-homebrew@b2a302b9a642580cae998e6ba2076ffd28e61317 # main

    - name: ⤵️ Install KSail
      shell: bash
      run: |
        brew tap devantler-tech/formulas
        brew install ksail
