name: 🔀 Enable Auto-Merge

on:
  pull_request:
  merge_group:

permissions: {}

jobs:
  auto-merge:
    uses: devantler-tech/reusable-workflows/.github/workflows/enable-auto-merge.yaml@5a334687e73feec66012e62db518716a8618417a # v3.0.0
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
