name: 🎉 Release

on:
  push:
    branches:
      - main

permissions: {}


jobs:
  release:
    uses: devantler-tech/reusable-workflows/.github/workflows/create-release.yaml@984aa9d877ef8618ec7c29cf3db7d7aa26931d5a # v3.1.1
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
