name: 🧪 enable-auto-merge-on-pr
on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  test-enable-auto-merge-on-pr:
    runs-on: ubuntu-latest
    if: startsWith(github.event_name, 'pull_request') && (github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'renovate[bot]' || github.event.pull_request.user.login == 'botantler[bot]' || github.event.pull_request.user.login == 'devantler')
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: 📑 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🧪 Run enable-auto-merge-on-pr
        uses: ./enable-auto-merge-on-pr
        with:
          app-id: ${{ vars.APP_ID }}
          app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  status-check:
    if: ${{ !cancelled() }}
    needs: [test-enable-auto-merge-on-pr]
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        env:
          RESULT: ${{ needs.test-enable-auto-merge-on-pr.result }}
        run: |
          if [[ "$RESULT" == "failure" ]]; then
            exit 1
          fi
