name: 🧪 enable-auto-merge-on-pr
on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  test-enable-auto-merge-on-pr:
    runs-on: ubuntu-latest
    if: startsWith(github.event_name, 'pull_request') && (github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'renovate[bot]' || github.event.pull_request.user.login == 'botantler[bot]' || github.event.pull_request.user.login == 'devantler')
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🧪 Run enable-auto-merge-on-pr
        uses: ./enable-auto-merge-on-pr
        with:
          pr-number: ${{ github.event.pull_request.number }}

  status-check:
    if: ${{ !cancelled() }}
    needs: [test-enable-auto-merge-on-pr]
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        env:
          RESULT: ${{ needs.test-enable-auto-merge-on-pr.result }}
        run: |
          if [[ "$RESULT" == "failure" ]]; then
            exit 1
          fi
